language: node_js
node_js:
  - "0.10"
sudo: required

before_install:
  - npm install wintersmith
before_script:
  - sudo apt-get install tree
script:
  - wintersmith build
after_success: 
  - cd build; tree; cd ..;
  - bash gh-pages-deploy.sh
branches:
  only:
    master
env: 
  global:
    secure: "W3JfAIkPMkDpuiJJeXpwUF05rsv1pU/DDcq6uBBuIlf9plYlE/HXj0T/zet1sEevQgZ6tFT1iAyQmkvUaRsbRWjYpSGwQFsyt79BrmR5AEfXjfduX1LPckYALxXfIA4CM7aqa3A6jioDlSbvogQ4QPG85i9m7CPISKOKYrWBXlU="